version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: tname_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    ports:
      - "8000:8000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    container_name: tname_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: tname_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:5.0
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - local_redis_data:/data

  celeryworker:
    <<: *django
    image: tname_local_celeryworker
    container_name: celeryworker
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: tname_local_celerybeat
    container_name: celerybeat
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: tname_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
