version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    container_name: django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs/gunicorn:/app/logs/gunicorn
      - ./tname/media:/app/tname/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    expose:
      - 8000
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    container_name: postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: always

  nginx:
    build: ./compose/production/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/etc/nginx/logs
      - ./tname/media:/app/tname/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  redis:
    image: redis:5.0
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - production_redis_data:/data
    restart: always

  celeryworker:
    <<: *django
    image: tname_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: tname_production_celerybeat
    command: /start-celerybeat
    volumes:
      - ./logs/celery:/app/logs/celery

  flower:
    <<: *django
    image: tname_production_flower
    command: /start-flower
    expose:
      - 5555
