version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    container_name: django
    depends_on:
      - postgres
    volumes:
      - ./logs/gunicorn:/app/logs/gunicorn
      - ./tname/media:/app/tname/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: bash -c "
      python /app/manage.py collectstatic --noinput &&
      python /app/manage.py migrate &&
      /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app --error-logfile /app/logs/gunicorn/error.log --access-logfile /app/logs/gunicorn/access.log --worker-tmp-dir=/dev/shm"
    expose:
      - 8000
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    container_name: postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: always

  nginx:
    build: ./compose/production/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/etc/nginx/logs
      - ./tname/media:/app/tname/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
