name: On push checks

on:
  push:
    branches-ignore:
      - master

jobs:
  linters_and_tests:
    name: run linters and tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "1.26.2"
      - name: build local
        run: docker-compose -f local.yml up --build --detach
      - name: wait for containers startup
        run: sleep 10
      - name: pylint
        run: docker exec tname_django bash -c "pylint tname"
      - name: pycodestyle
        run: docker exec tname_django bash -c "pycodestyle tname"
      - name: isort
        run: docker exec tname_django bash -c "isort tname"
      - name: run tests
        run: docker exec tname_django bash -c "python manage.py test --settings config.settings.test --parallel --failfast"
